// Minimal OAuth 2.1 shim + reverse proxy in front of n8n-mcp (HTTP mode).
//
// n8n-mcp authenticates with a static Bearer AUTH_TOKEN, but Claude/Cowork's
// custom connector UI only speaks OAuth (or no auth at all) to remote MCP
// servers. This service sits in between:
//
//   Cowork  --OAuth-->  this proxy  --Bearer UPSTREAM_AUTH_TOKEN-->  n8n-mcp
//
// It implements just enough OAuth 2.1 (discovery, dynamic client
// registration, authorization code + PKCE, refresh tokens) for Cowork's
// connector flow to complete, gated by a single shared password so random
// visitors can't get a token. Everything is kept in memory, fine for a
// single-user deployment; state resets on restart (Cowork will just re-auth).

const express = require('express');
const crypto = require('crypto');
const { createProxyMiddleware } = require('http-proxy-middleware');

const {
  PORT = '3000',
    BASE_URL,
      UPSTREAM_MCP_URL,
        UPSTREAM_AUTH_TOKEN,
          LOGIN_PASSWORD,
            ACCESS_TOKEN_TTL_SECONDS = '3600',
              REFRESH_TOKEN_TTL_SECONDS = String(60 * 60 * 24 * 90),
              } = process.env;

              for (const [name, val] of Object.entries({ BASE_URL, UPSTREAM_MCP_URL, UPSTREAM_AUTH_TOKEN, LOGIN_PASSWORD })) {
                if (!val) {
                    console.error('Missing required env var: ' + name);
                        process.exit(1);
                          }
                          }

                          const upstream = new URL(UPSTREAM_MCP_URL);
                          const UPSTREAM_ORIGIN = upstream.origin;
                          const UPSTREAM_PATH = upstream.pathname || '/mcp';

                          const app = express();
                          app.disable('x-powered-by');

                          const clients = new Map();
                          const authCodes = new Map();
                          const accessTokens = new Map();
                          const refreshTokens = new Map();

                          function randomToken(bytes = 32) {
                            return crypto.randomBytes(bytes).toString('base64url');
                            }

                            function purgeExpired(map) {
                              const now = Date.now();
                                for (const [key, val] of map.entries()) {
                                    if (val.expires && val.expires < now) map.delete(key);
                                      }
                                      }

                                      function escapeHtml(str) {
                                        return String(str).replace(/[&<>"']/g, (c) => ({
                                            '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
                                              }[c]));
                                              }

                                              const authServerMetadata = {
                                                issuer: BASE_URL,
                                                  authorization_endpoint: BASE_URL + '/authorize',
                                                    token_endpoint: BASE_URL + '/token',
                                                      registration_endpoint: BASE_URL + '/register',
                                                        response_types_supported: ['code'],
                                                          grant_types_supported: ['authorization_code', 'refresh_token'],
                                                            code_challenge_methods_supported: ['S256', 'plain'],
                                                              token_endpoint_auth_methods_supported: ['client_secret_post', 'client_secret_basic', 'none'],
                                                                scopes_supported: ['mcp'],
                                                                };

                                                                app.get(
                                                                  ['/.well-known/oauth-authorization-server', '/.well-known/oauth-authorization-server/*'],
                                                                    (req, res) => res.json(authServerMetadata)
                                                                    );

                                                                    app.get(
                                                                      ['/.well-known/oauth-protected-resource', '/.well-known/oauth-protected-resource/*'],
                                                                        (req, res) => res.json({
                                                                            resource: BASE_URL + UPSTREAM_PATH,
                                                                                authorization_servers: [BASE_URL],
                                                                                  })
                                                                                  );

                                                                                  app.post('/register', express.json(), (req, res) => {
                                                                                    const { redirect_uris, client_name, token_endpoint_auth_method } = req.body || {};
                                                                                      if (!Array.isArray(redirect_uris) || redirect_uris.length === 0) {
                                                                                          return res.status(400).json({ error: 'invalid_client_metadata', error_description: 'redirect_uris is required' });
                                                                                            }
                                                                                              const client_id = randomToken(16);
                                                                                                const client_secret = randomToken(24);
                                                                                                  clients.set(client_id, { client_secret, redirect_uris });
                                                                                                    res.status(201).json({
                                                                                                        client_id,
                                                                                                            client_secret,
                                                                                                                client_id_issued_at: Math.floor(Date.now() / 1000),
                                                                                                                    client_secret_expires_at: 0,
                                                                                                                        redirect_uris,
                                                                                                                            client_name: client_name || 'MCP Client',
                                                                                                                                token_endpoint_auth_method: token_endpoint_auth_method || 'client_secret_post',
                                                                                                                                    grant_types: ['authorization_code', 'refresh_token'],
                                                                                                                                        response_types: ['code'],
                                                                                                                                          });
                                                                                                                                          });
                                                                                                                                          
                                                                                                                                          app.get('/authorize', (req, res) => {
                                                                                                                                            const { client_id, redirect_uri, response_type, state, code_challenge, code_challenge_method } = req.query;
                                                                                                                                              if (response_type !== 'code') return res.status(400).send('unsupported response_type');
                                                                                                                                                const client = clients.get(client_id);
                                                                                                                                                  if (!client) return res.status(400).send('unknown client_id (register first)');
                                                                                                                                                    if (!client.redirect_uris.includes(redirect_uri)) return res.status(400).send('redirect_uri mismatch');
                                                                                                                                                    
                                                                                                                                                      const hidden = {
                                                                                                                                                          client_id,
                                                                                                                                                              redirect_uri,
                                                                                                                                                                  state: state || '',
                                                                                                                                                                      code_challenge: code_challenge || '',
                                                                                                                                                                          code_challenge_method: code_challenge_method || 'plain',
                                                                                                                                                                            };
                                                                                                                                                                            
                                                                                                                                                                              const inputs = Object.entries(hidden).map(function (entry) {
                                                                                                                                                                                  return '<input type="hidden" name="' + entry[0] + '" value="' + escapeHtml(entry[1]) + '">';
                                                                                                                                                                                    }).join('\n    ');
                                                                                                                                                                                    
                                                                                                                                                                                      const page = '<!doctype html>\n' +
                                                                                                                                                                                          '<html><head><meta charset="utf-8"><title>Autorizar n8n-mcp</title></head>\n' +
                                                                                                                                                                                              '<body style="font-family:system-ui,sans-serif;max-width:420px;margin:80px auto;color:#222;">\n' +
                                                                                                                                                                                                  '  <h2>Autorizar acceso a n8n-mcp</h2>\n' +
                                                                                                                                                                                                      '  <p>Un cliente MCP esta pidiendo acceso a tu servidor n8n-mcp.</p>\n' +
                                                                                                                                                                                                          '  <form method="POST" action="/authorize">\n' +
                                                                                                                                                                                                              '    ' + inputs + '\n' +
                                                                                                                                                                                                                  '    <label for="password">Contrasena</label><br/>\n' +
                                                                                                                                                                                                                      '    <input id="password" type="password" name="password" style="width:100%;padding:8px;margin:8px 0;box-sizing:border-box;" autofocus/><br/>\n' +
                                                                                                                                                                                                                          '    <button type="submit" style="padding:8px 16px;">Autorizar</button>\n' +
                                                                                                                                                                                                                              '  </form>\n' +
                                                                                                                                                                                                                                  '</body></html>';
                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                    res.send(page);
                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                    app.post('/authorize', express.urlencoded({ extended: true }), (req, res) => {
                                                                                                                                                                                                                                      const { client_id, redirect_uri, state, code_challenge, code_challenge_method, password } = req.body;
                                                                                                                                                                                                                                        const client = clients.get(client_id);
                                                                                                                                                                                                                                          if (!client || !client.redirect_uris.includes(redirect_uri)) {
                                                                                                                                                                                                                                              return res.status(400).send('invalid client or redirect_uri');
                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                  if (password !== LOGIN_PASSWORD) {
                                                                                                                                                                                                                                                      return res.status(401).send('Contrasena incorrecta. Volve atras e intenta de nuevo.');
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                          const code = randomToken(24);
                                                                                                                                                                                                                                                            authCodes.set(code, {
                                                                                                                                                                                                                                                                client_id,
                                                                                                                                                                                                                                                                    redirect_uri,
                                                                                                                                                                                                                                                                        code_challenge,
                                                                                                                                                                                                                                                                            code_challenge_method,
                                                                                                                                                                                                                                                                                expires: Date.now() + 5 * 60 * 1000,
                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                    const url = new URL(redirect_uri);
                                                                                                                                                                                                                                                                                      url.searchParams.set('code', code);
                                                                                                                                                                                                                                                                                        if (state) url.searchParams.set('state', state);
                                                                                                                                                                                                                                                                                          res.redirect(url.toString());
                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                          app.post('/token', express.urlencoded({ extended: true }), express.json(), (req, res) => {
                                                                                                                                                                                                                                                                                            purgeExpired(authCodes);
                                                                                                                                                                                                                                                                                              purgeExpired(accessTokens);
                                                                                                                                                                                                                                                                                                purgeExpired(refreshTokens);
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                  const { grant_type } = req.body;
                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                    if (grant_type === 'authorization_code') {
                                                                                                                                                                                                                                                                                                        const { code, redirect_uri, client_id, code_verifier } = req.body;
                                                                                                                                                                                                                                                                                                            const entry = authCodes.get(code);
                                                                                                                                                                                                                                                                                                                if (!entry || entry.client_id !== client_id || entry.redirect_uri !== redirect_uri) {
                                                                                                                                                                                                                                                                                                                      return res.status(400).json({ error: 'invalid_grant' });
                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                              authCodes.delete(code);
                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                  if (entry.code_challenge) {
                                                                                                                                                                                                                                                                                                                                        const computed = entry.code_challenge_method === 'S256'
                                                                                                                                                                                                                                                                                                                                                ? crypto.createHash('sha256').update(code_verifier || '').digest('base64url')
                                                                                                                                                                                                                                                                                                                                                        : (code_verifier || '');
                                                                                                                                                                                                                                                                                                                                                              if (computed !== entry.code_challenge) {
                                                                                                                                                                                                                                                                                                                                                                      return res.status(400).json({ error: 'invalid_grant', error_description: 'PKCE verification failed' });
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                    const access_token = randomToken(32);
                                                                                                                                                                                                                                                                                                                                                                                        const refresh_token = randomToken(32);
                                                                                                                                                                                                                                                                                                                                                                                            accessTokens.set(access_token, { client_id, expires: Date.now() + Number(ACCESS_TOKEN_TTL_SECONDS) * 1000 });
                                                                                                                                                                                                                                                                                                                                                                                                refreshTokens.set(refresh_token, { client_id, expires: Date.now() + Number(REFRESH_TOKEN_TTL_SECONDS) * 1000 });
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                    return res.json({
                                                                                                                                                                                                                                                                                                                                                                                                          access_token,
                                                                                                                                                                                                                                                                                                                                                                                                                token_type: 'Bearer',
                                                                                                                                                                                                                                                                                                                                                                                                                      expires_in: Number(ACCESS_TOKEN_TTL_SECONDS),
                                                                                                                                                                                                                                                                                                                                                                                                                            refresh_token,
                                                                                                                                                                                                                                                                                                                                                                                                                                  scope: 'mcp',
                                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                          if (grant_type === 'refresh_token') {
                                                                                                                                                                                                                                                                                                                                                                                                                                              const { refresh_token, client_id } = req.body;
                                                                                                                                                                                                                                                                                                                                                                                                                                                  const entry = refreshTokens.get(refresh_token);
                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!entry || entry.client_id !== client_id) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                            return res.status(400).json({ error: 'invalid_grant' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const access_token = randomToken(32);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        accessTokens.set(access_token, { client_id, expires: Date.now() + Number(ACCESS_TOKEN_TTL_SECONDS) * 1000 });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return res.json({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  access_token,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        token_type: 'Bearer',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              expires_in: Number(ACCESS_TOKEN_TTL_SECONDS),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    refresh_token,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          scope: 'mcp',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  res.status(400).json({ error: 'unsupported_grant_type' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  function requireBearer(req, res, next) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const auth = req.headers['authorization'] || '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const token = auth.startsWith('Bearer ') ? auth.slice(7) : null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const entry = token && accessTokens.get(token);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!entry || (entry.expires && entry.expires < Date.now())) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              res.set('WWW-Authenticate', 'Bearer resource_metadata="' + BASE_URL + '/.well-known/oauth-protected-resource"');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return res.status(401).json({ error: 'invalid_token' });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      next();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      app.get('/health', (req, res) => res.json({ status: 'ok', proxy: true }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      app.use(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        UPSTREAM_PATH,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          requireBearer,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            createProxyMiddleware({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                target: UPSTREAM_ORIGIN,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    changeOrigin: true,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ws: false,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onProxyReq: (proxyReq) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  proxyReq.setHeader('Authorization', 'Bearer ' + UPSTREAM_AUTH_TOKEN);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        app.listen(Number(PORT), () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          console.log('n8n-mcp OAuth proxy listening on :' + PORT);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log('BASE_URL=' + BASE_URL);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              console.log('Proxying ' + UPSTREAM_PATH + ' -> ' + UPSTREAM_ORIGIN + UPSTREAM_PATH);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
